### ISSUE TITLE
\url not interpreted

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor-bibtex#13]
Hello, 
I stumbled over a similar one:

```
@misc{berinato2007,
  title = {The {{Rise}} of {{Anti Forensics}}.},
  timestamp = {2016-09-12T11:08:23Z},
  urldate = {2016-08-25},
  howpublished = {\url{http://www.csoonline.com/article/2122329/investigations-forensics/the-rise-of-anti-forensics.html}},
  journal = {CSO Online},
  author = {Berinato, Scott},
  month = aug,
  year = {2007}
}
```

which is rendered as follows:

S. Berinato, “The Rise of Anti Forensics.,” CSO Online. \urlhttp://www.csoonline.com/article/2122329/investigations-forensics/the-rise-of-anti-forensics.html, Aug-2007.

Please note "\url...".

**Comment by ProgramFan** [comment]
Thanks @getreu . bibtex-ruby only handles latex macros which can be converted to unicode symbols. Now I need to write latex filter myself.

**Comment by getreu** [comment]
Thank you. I think it is worth. BTW: the samples I sent you are generated with zotero's plugin "BetterBibtex".

**Comment by ProgramFan** [comment]
Since bibtex-ruby processes latex structs that can be convert to unicode, this package will use simple huristics to handle other latex structs:

1. known latex macros such as `\url` are converted to their asciidoc equivalence.
2. if not known, single latex structs matched by `\\\w+` is ignored.
3. if not known, macros with parameters matched by `\\\w+(?:\[[^]]+\])?\{([^}]+)\}` is replaced by `\1`, i.e., replaced by the macro contents. 

There are just too many latex macros to consider. So the above approach allows for adding special macros incrementally while remains useful if macros are not recoganized.

**Comment by getreu** [comment]
It works. Thank you!
