### ISSUE TITLE
dash in citation key causes it to be ignored

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor-bibtex#16]
If there is a dash (-) in the citation key (such as cite:[fernandez-lopez_overview_2002]) the whole citation is ignored. This was actually a problem with asciidoc-bib also which were fixed: https://github.com/petercrlane/asciidoc-bib/commit/397939f1950f9612b136a7d9c8d0f3859cdf3364

**Comment by ProgramFan** [comment]
I understand the issue. The regex used for retrieving citations allows only alphanumerics and underscore. Are there any definitions on what chars are allowed in bibtex keys?

**Comment by shahryareiv** [comment]
Actually there is no restriction or at least dash is permitted. My bibkeys are automatically build by Zotero (with or without Better BibTex extension) and those dashed are generated by them automatically. In asciidoc-bib there was the same problem which I commented then and the repository author just fixed it the day after. I put the link in my comment above for the reference.

**Comment by ProgramFan** [comment]
Fixed by  e742378. I have tested it on my laptop and it works for citations like 'guo:333-aa_bb'. New versions is not yet scheduled, so please use the master branch directly at the moment.

**Comment by shahryareiv** [comment]
Thanks a lot!

**Comment by shahryareiv** [comment]
I don't have Ruby knowledge maybe I am asking a trivial question, but the `bin` folder does not exists in asciidoctor-bibtex project anymore (I notice it exists in asciidoctor-bib as well as asciidoctor-bibtex gem file) . This happened in commit of 15 Sep I guess ("Remove commandline utilities "). So I wonder how one should refer asciidoc-bibtex (for adoc to adoc transfer) in the master branch?

**Comment by ProgramFan** [comment]
We remove it in version 0.2.0 because we want to remove the associated maintainance burden. The asiidoc to asciidoc transfer mechanism requires quite a different implementation and has several limitations (for example, not possible to support citations breaking up in two lines). We recommend using asciidoctor-bibtex as an asciidoctor extension, so you can use all nice features from asciidoctor and its friends. However, you can always use 0.1.0 for asciidoc-bibtex and it still works.
